// Generated by nitro
import type { Serialize, Simplify } from "nitropack/types";
declare module "nitropack/types" {
  type Awaited<T> = T extends PromiseLike<infer U> ? Awaited<U> : T
  interface InternalApi {
    '/api/chat': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/chat.post').default>>>>
    }
    '/api/models': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/models.get').default>>>>
    }
    '/api/_hub/**:feature': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/.pnpm/@nuxthub+core@0.8.25_@netli_ef8ef756493a226951ee428c14adf03b/node_modules/@nuxthub/core/dist/runtime/base/server/api/_hub/[...feature]').default>>>>
    }
    '/api/_hub': {
      'head': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/.pnpm/@nuxthub+core@0.8.25_@netli_ef8ef756493a226951ee428c14adf03b/node_modules/@nuxthub/core/dist/runtime/base/server/api/_hub/index.head').default>>>>
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/.pnpm/@nuxthub+core@0.8.25_@netli_ef8ef756493a226951ee428c14adf03b/node_modules/@nuxthub/core/dist/runtime/cors.dev').default>>>>
    }
    '/api/_hub/manifest': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/.pnpm/@nuxthub+core@0.8.25_@netli_ef8ef756493a226951ee428c14adf03b/node_modules/@nuxthub/core/dist/runtime/base/server/api/_hub/manifest.get').default>>>>
    }
    '/api/_hub/ai/:command': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/.pnpm/@nuxthub+core@0.8.25_@netli_ef8ef756493a226951ee428c14adf03b/node_modules/@nuxthub/core/dist/runtime/ai/server/api/_hub/ai/[command].post').default>>>>
    }
    '/api/_hub/cache/**:key': {
      'delete': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/.pnpm/@nuxthub+core@0.8.25_@netli_ef8ef756493a226951ee428c14adf03b/node_modules/@nuxthub/core/dist/runtime/cache/server/api/_hub/cache/[...key].delete').default>>>>
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/.pnpm/@nuxthub+core@0.8.25_@netli_ef8ef756493a226951ee428c14adf03b/node_modules/@nuxthub/core/dist/runtime/cache/server/api/_hub/cache/[...key].get').default>>>>
      'options': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/.pnpm/@nuxthub+core@0.8.25_@netli_ef8ef756493a226951ee428c14adf03b/node_modules/@nuxthub/core/dist/runtime/cache/server/api/_hub/cache/[...key].options').default>>>>
    }
    '/api/_hub/cache/batch-delete': {
      'options': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/.pnpm/@nuxthub+core@0.8.25_@netli_ef8ef756493a226951ee428c14adf03b/node_modules/@nuxthub/core/dist/runtime/cache/server/api/_hub/cache/batch-delete.options').default>>>>
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/.pnpm/@nuxthub+core@0.8.25_@netli_ef8ef756493a226951ee428c14adf03b/node_modules/@nuxthub/core/dist/runtime/cache/server/api/_hub/cache/batch-delete.post').default>>>>
    }
    '/api/_hub/cache/clear/**:base': {
      'delete': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/.pnpm/@nuxthub+core@0.8.25_@netli_ef8ef756493a226951ee428c14adf03b/node_modules/@nuxthub/core/dist/runtime/cache/server/api/_hub/cache/clear/[...base].delete').default>>>>
      'options': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/.pnpm/@nuxthub+core@0.8.25_@netli_ef8ef756493a226951ee428c14adf03b/node_modules/@nuxthub/core/dist/runtime/cache/server/api/_hub/cache/clear/[...base].options').default>>>>
    }
    '/api/_hub/cache': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/.pnpm/@nuxthub+core@0.8.25_@netli_ef8ef756493a226951ee428c14adf03b/node_modules/@nuxthub/core/dist/runtime/cache/server/api/_hub/cache/index.get').default>>>>
    }
    '/__nuxt_error': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/.pnpm/nuxt@3.16.2_@netlify+blobs@_62309875d312af78dc77de795c861029/node_modules/nuxt/dist/core/runtime/nitro/handlers/renderer').default>>>>
    }
    '/api/_nuxt_icon/:collection': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/.pnpm/@nuxt+icon@1.12.0_magicast@_0a51225c00c22cb49de8ac98e5644acc/node_modules/@nuxt/icon/dist/runtime/server/api').default>>>>
    }
  }
}
export {}